#License
#=======
#  Copyright (c) 2014 Genome Research Ltd. 
#
#    Author: James Beal <James.Beal@sanger.ac.uk>
#
#    This file is part of Objectbench. 
#
#      Objectbench is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version. 
#        This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. 
#          You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>. 
#
defaults: &defaults
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: true
  username:  <%= ENV['OBJECTBENCH_DB_USER'] %>
  password:  <%= ENV['OBJECTBENCH_DB_PASS'] %> 
  host:      <%= ENV['OBJECTBENCH_DB_HOST'] %>


development:
  <<: *defaults
  database: <%= ENV['OBJECTBENCH_DB_SCHEMA_DEV'] %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *defaults
  database: <%= ENV['OBJECTBENCH_DB_SCHEMA_TEST'] %>

production:
  <<: *defaults
  database: <%= ENV['OBJECTBENCH_DB_SCHEMA_PRODUCTION'] %>
