test: <%= ENV['OBJECTBENCH_REDIS_HOST'] %>: <%= ENV['OBJECTBENCH_REDIS_PORT'] %>
development: <%= ENV['OBJECTBENCH_REDIS_HOST'] %>: <%= ENV['OBJECTBENCH_REDIS_PORT'] %>
production: <%= ENV['OBJECTBENCH_REDIS_HOST'] %>: <%= ENV['OBJECTBENCH_REDIS_PORT'] %>
