#!/bin/bash
kill  `ps -ef |grep resqu  | awk '{print $2}'` &> /dev/null 
kill  `ps -ef |grep "curl --noproxy"  | awk '{print $2}'` &> /dev/null
sleep 2
kill -9  `ps -ef |grep resqu  | awk '{print $2}'` &> /dev/null
kill -9 `ps -ef |grep "curl --noproxy"  | awk '{print $2}'` &> /dev/null
PHANTOM_HOST="`uname -n`" bundle exec rake object_bench:delete_phantom_workers
