#!/bin/bash
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"
export OBJECTBENCH_SYSTEM_UNDER_TEST="CleverSafe"
. "$( dirname "${BASH_SOURCE[0]}" )/config" 
setup_two_read_write_test
export OBJECTBENCH_INITAL_DISTRIBUTION="86, 103, 68, 113"
two_phase_test
